const StatusMap: {
    [key: number]: string
} = {
    400: "Bad Request",
    401: "Unauthorized",
    402: "Payment Required",
    403: "Forbidden",
    404: "Not Found",
    405: "Method Not Allowed",
    406: "Not Acceptable",
    407: "Proxy Authentication Required",
    408: "Request Timeout",
    409: "Conflict",
    410: "Gone",
    411: "Length Required",
    412: "Precondition Failed",
    413: "Payload Too Large",
    414: "URI Too Long",
    415: "Unsupported Media Type",
    416: "Range Not Satisfiable",
    417: "Expectation Failed",
    418: "I'm a teapot",
    421: "Misdirected Request",
    422: "Unprocessable Entity",
    423: "Locked",
    424: "Failed Dependency",
    425: "Too Early",
    426: "Upgrade Required",
    428: "Precondition Required",
    429: "Too Many Requests",
    431: "Request Header Fields Too Large",
    451: "Unavailable For Legal Reasons",
    500: "Internal Server Error",
    501: "Not Implemented",
    502: "Bad Gateway",
    503: "Service Unavailable",
    504: "Gateway Timeout",
    505: "HTTP Version Not Supported",
    506: "Variant Also Negotiates",
    507: "Insufficient Storage",
    508: "Loop Detected",
    510: "Not Extended",
    511: "Network Authentication Required"
}

const status_code_str = document.title;
const status_code = Number(status_code_str);
let status_name = "Unknown Error";

if (status_code in StatusMap) {
    status_name = StatusMap[status_code];
}

document.title = status_code_str + " " + status_name;
(document.getElementById("status") as HTMLSpanElement).innerText = status_code_str;
(document.getElementById("status-name") as HTMLSpanElement).innerText = status_name;

if (status_code > 399 && status_code < 500) {
    (document.getElementById("client-icon") as HTMLSpanElement).classList.remove("hidden");
} else if (status_code > 499 && status_code < 600) {
    (document.getElementById("server-icon") as HTMLSpanElement).classList.remove("hidden");
} else {
    (document.getElementById("error-icon") as HTMLSpanElement).classList.remove("hidden");
}

(document.getElementById("URL") as HTMLParagraphElement).innerText = location.href;
const date = new Date();
let client_time = date.getFullYear().toString();
client_time += "-" + (date.getUTCMonth() + 1).toString().padStart(2, "0");
client_time += "-" + date.getUTCDate().toString().padStart(2, "0");
client_time += " " + date.getUTCHours().toString().padStart(2, "0");
client_time += ":" + date.getUTCMinutes().toString().padStart(2, "0");
client_time += ":" + date.getUTCSeconds().toString().padStart(2, "0");
client_time += " UTC";
(document.getElementById("client-time") as HTMLParagraphElement).innerText = client_time;

// source: https://www.cloudflarestatus.com
const CFDataCenterMap: { [key: string]: string } = {
    // ABQ: "Albuquerque, NM, United States",
    ABQ: "Albuquerque",
    ACC: "Accra, Ghana",
    ADB: "Izmir, Turkey",
    ADL: "Adelaide, SA, Australia",
    AKL: "Auckland, New Zealand",
    ALA: "Almaty, Kazakhstan",
    ALG: "Algiers, Algeria",
    AMD: "Ahmedabad, India",
    AMM: "Amman, Jordan",
    AMS: "Amsterdam, Netherlands",
    ARI: "Arica, Chile",
    ARN: "Stockholm, Sweden",
    ASU: "Asunción, Paraguay",
    ATH: "Athens, Greece",
    ATL: "Atlanta, GA, United States",
    AUS: "Austin",
    BAH: "Manama, Bahrain",
    BBI: "Bhubaneswar, India",
    BCN: "Barcelona, Spain",
    BEG: "Belgrade, Serbia",
    BEL: "Belém, Brazil",
    BEY: "Beirut, Lebanon",
    // BGR: "Bangor ME, USA",
    BGR: "Bangor",
    BGW: "Baghdad, Iraq",
    BKK: "Bangkok, Thailand",
    BLR: "Bangalore, India",
    BNA: "Nashville, United States",
    BNE: "Brisbane, QLD, Australia",
    BNU: "Blumenau, Brazil",
    BOG: "Bogotá, Colombia",
    BOM: "Mumbai, India",
    BOS: "Boston, MA, United States",
    BRU: "Brussels, Belgium",
    BSB: "Brasilia, Brazil",
    BSR: "Basra, Iraq",
    BTS: "Bratislava, Slovakia",
    BUD: "Budapest, Hungary",
    BUF: "Buffalo, NY, United States",
    BWN: "Bandar Seri Begawan, Brunei",
    CAN: "Guangzhou, China",
    CAW: "Campos dos Goytacazes",
    CBR: "Canberra, ACT, Australia",
    CCP: "Concepción, Chile",
    CCU: "Kolkata, India",
    CDG: "Paris, France",
    CEB: "Cebu, Philippines",
    CFC: "Caçador, Brazil",
    CGB: "Cuiabá, Brazil",
    CGD: "Changde, China",
    CGK: "Jakarta, Indonesia",
    CGO: "Zhengzhou, China",
    CGP: "Chittagong, Bangladesh",
    CGQ: "Changchun, China",
    CGY: "Cagayan de Oro, Philippines",
    CHC: "Christchurch, New Zealand",
    CLT: "Charlotte, NC, United States",
    CMB: "Colombo, Sri Lanka",
    CMH: "Columbus, OH, United States",
    CMN: "Casablanca, Morocco",
    CNF: "Belo Horizonte, Brazil",
    CNX: "Chiang Mai, Thailand",
    COK: "Kochi",
    COR: "Córdoba, Argentina",
    CPH: "Copenhagen, Denmark",
    CPT: "Cape Town, South Africa",
    CSX: "Changsha, China",
    CUR: "Willemstad, Curaçao",
    CWB: "Curitiba, Brazil",
    DAC: "Dhaka, Bangladesh",
    DAR: "Dar Es Salaam, Tanzania",
    DEL: "New Delhi, India",
    DEN: "Denver, CO, United States",
    DFW: "Dallas, TX, United States",
    DKR: "Dakar, Senegal",
    DME: "Moscow, Russia",
    DMM: "Dammam, Saudi Arabia",
    DOH: "Doha, Qatar",
    DTW: "Detroit, MI, United States",
    DUB: "Dublin, Ireland",
    DUR: "Durban, South Africa",
    DUS: "Düsseldorf, Germany",
    DXB: "Dubai, United Arab Emirates",
    EBL: "Erbil, Iraq",
    EDI: "Edinburgh, United Kingdom",
    EVN: "Yerevan, Armenia",
    EWR: "Newark, NJ, United States",
    EZE: "Buenos Aires, Argentina",
    FCO: "Rome, Italy",
    FIH: "Kinshasa",
    FLN: "Florianopolis, Brazil",
    FOC: "Fuzhou, China",
    FOR: "Fortaleza, Brazil",
    FRA: "Frankfurt, Germany",
    FSD: "Sioux Falls, South Dakota",
    FUK: "Fukuoka, Japan",
    FUO: "Foshan, China",
    GBE: "Gaborone, Botswana",
    GEO: "Georgetown, Guyana",
    GIG: "Rio de Janeiro, Brazil",
    GND: "St. George's, Grenada",
    GOT: "Gothenburg, Sweden",
    GRU: "São Paulo, Brazil",
    GUA: "Guatemala City, Guatemala",
    GUM: "Hagatna, Guam",
    GVA: "Geneva, Switzerland",
    GYD: "Baku, Azerbaijan",
    GYE: "Guayaquil, Ecuador",
    GYN: "Goiânia, Brazil",
    HAK: "Haikou, China",
    HAM: "Hamburg, Germany",
    HAN: "Hanoi, Vietnam",
    HBA: "Hobart, Australia",
    HEL: "Helsinki, Finland",
    HFA: "Haifa, Israel",
    HKG: "Hong Kong",
    HNL: "Honolulu, HI, United States",
    HRE: "Harare, Zimbabwe",
    HYD: "Hyderabad, India",
    HYN: "Taizhou",
    IAD: "Ashburn, VA, United States",
    IAH: "Houston, TX, United States",
    ICN: "Seoul, South Korea",
    IND: "Indianapolis, IN, United States",
    ISB: "Islamabad, Pakistan",
    IST: "Istanbul, Turkey",
    ISU: "Sulaymaniyah, Iraq",
    ITJ: "Itajaí, Brazil",
    IXC: "Chandigarh, IN",
    JAX: "Jacksonville, FL, United States",
    JDO: "Juazeiro do Norte, Brazil",
    JED: "Jeddah, Saudi Arabia",
    JHB: "Johor Bahru, Malaysia",
    JIB: "Djibouti City, Djibouti",
    JNB: "Johannesburg, South Africa",
    JOG: "Yogyakarta, Indonesia",
    JOI: "Joinville, Brazil",
    JSR: "Jashore, Bangladesh",
    KBP: "Kyiv, Ukraine",
    KEF: "Reykjavík, Iceland",
    KGL: "Kigali, Rwanda",
    KHH: "Kaohsiung City",
    KHI: "Karachi, Pakistan",
    KHN: "Xinyu, China",
    KHV: "Khabarovsk, Russia",
    KIN: "Kingston",
    KIV: "Chișinău, Moldova",
    KIX: "Osaka, Japan",
    KJA: "Krasnoyarsk, Russia",
    KLD: "Tver, Russian Federation",
    KNU: "Kanpur, India",
    KTM: "Kathmandu, Nepal",
    KUL: "Kuala Lumpur, Malaysia",
    KWI: "Kuwait City, Kuwait",
    LAD: "Luanda, Angola",
    LAS: "Las Vegas, NV, United States",
    LAX: "Los Angeles, CA, United States",
    LCA: "Nicosia, Cyprus",
    LED: "Saint Petersburg, Russia",
    LHE: "Lahore, Pakistan",
    LHR: "London, United Kingdom",
    LHW: "Lanzhou, China",
    LIM: "Lima, Peru",
    LIS: "Lisbon, Portugal",
    LLK: "Astara, Azerbaijan",
    LOS: "Lagos, Nigeria",
    LUX: "Luxembourg City, Luxembourg",
    LYA: "Luoyang, China",
    LYS: "Lyon",
    MAA: "Chennai, India",
    MAD: "Madrid, Spain",
    MAN: "Manchester, United Kingdom",
    MAO: "Manaus, Brazil",
    MBA: "Mombasa, Kenya",
    MCI: "Kansas City, MO, United States",
    MCT: "Muscat, Oman",
    MDE: "Medellín, Colombia",
    MDL: "Mandalay, Myanmar",
    MEL: "Melbourne, VIC, Australia",
    MEM: "Memphis, TN, United States",
    MEX: "Mexico City, Mexico",
    MFE: "McAllen, TX, United States",
    MFM: "Macau",
    MGM: "Montgomery, AL, United States",
    MIA: "Miami, FL, United States",
    MLE: "Malé, Maldives",
    MNL: "Manila, Philippines",
    MPM: "Maputo, Mozambique",
    MRS: "Marseille, France",
    MRU: "Port Louis, Mauritius",
    MSP: "Minneapolis, MN, United States",
    MSQ: "Minsk, Belarus",
    MUC: "Munich, Germany",
    MXP: "Milan, Italy",
    NAG: "Nagpur, India",
    NBO: "Nairobi, Kenya",
    NJF: "Najaf, Iraq",
    NOU: "Noumea, New Caledonia",
    NQN: "Neuquén, Argentina",
    NRT: "Tokyo, Japan",
    NTG: "Nantong",
    NVT: "Timbó, Brazil",
    OKA: "Naha, Japan",
    OMA: "Omaha, NE, United States",
    ORD: "Chicago, IL, United States",
    ORF: "Norfolk, VA, United States",
    ORK: "Cork, Ireland",
    ORN: "Oran",
    OSL: "Oslo, Norway",
    OTP: "Bucharest, Romania",
    OUA: "Ouagadougou, Burkina Faso",
    PAP: "Port-Au-Prince, Haiti",
    PAT: "Patna, India",
    PBH: "Thimphu, Bhutan",
    PBM: "Paramaribo, Suriname",
    PDX: "Portland, OR, United States",
    PER: "Perth, WA, Australia",
    PHL: "Philadelphia, United States",
    PHX: "Phoenix, AZ, United States",
    PIT: "Pittsburgh, PA, United States",
    PKX: "Langfang, China",
    PMO: "Palermo, Italy",
    PNH: "Phnom Penh, Cambodia",
    POA: "Porto Alegre, Brazil",
    PPT: "Tahiti, French Polynesia",
    PRG: "Prague, Czech Republic",
    PTY: "Panama City, Panama",
    QRO: "Queretaro, MX, Mexico",
    QWJ: "Americana, Brazil",
    RAO: "Ribeirao Preto, Brazil",
    REC: "Recife",
    RGN: "Yangon, Myanmar",
    RIC: "Richmond, VA, United States",
    RIX: "Riga, Latvia",
    RUH: "Riyadh, Saudi Arabia",
    RUN: "Réunion, France",
    SAN: "San Diego, CA, United States",
    SCL: "Santiago, Chile",
    SDQ: "Santo Domingo, Dominican Republic",
    SEA: "Seattle, WA, United States",
    SFO: "San Francisco",
    SGN: "Ho Chi Minh City, Vietnam",
    SHA: "Shanghai, China",
    SIN: "Singapore, Singapore",
    SJC: "San Jose, CA, United States",
    SJK: "São José dos Campos, Brazil",
    SJO: "San José, Costa Rica",
    SJP: "São José do Rio Preto, Brazil",
    SJW: "Hengshui, China",
    SKG: "Thessaloniki, Greece",
    SLC: "Salt Lake City, UT, United States",
    SMF: "Sacramento, CA, United States",
    SOD: "Sorocaba, Brazil",
    SOF: "Sofia, Bulgaria",
    SSA: "Salvador, Brazil",
    STL: "St. Louis, MO, United States",
    STR: "Stuttgart, Germany",
    SVX: "Yekaterinburg, Russia",
    SYD: "Sydney, NSW, Australia",
    TAO: "Qingdao, China",
    TAS: "Tashkent, Uzbekistan",
    TBS: "Tbilisi, Georgia",
    TGU: "Tegucigalpa, Honduras",
    TIA: "Tirana, Albania",
    TLH: "Tallahassee, FL, United States",
    TLL: "Tallinn, Estonia",
    TLV: "Tel Aviv, Israel",
    TNA: "Jinan, China",
    TNR: "Antananarivo, Madagascar",
    TPA: "Tampa, FL, United States",
    TPE: "Taipei",
    TSN: "Tianjin, China",
    TUN: "Tunis, Tunisia",
    TXL: "Berlin, Germany",
    TYN: "Datong, China",
    UDI: "Uberlândia, Brazil",
    UIO: "Quito, Ecuador",
    ULN: "Ulaanbaatar, Mongolia",
    URT: "Surat Thani, Thailand",
    VCP: "Campinas, Brazil",
    VIE: "Vienna, Austria",
    VIX: "Vitoria, Brazil",
    VNO: "Vilnius, Lithuania",
    VTE: "Vientiane, Laos",
    WAW: "Warsaw, Poland",
    WHU: "Wuhu",
    WUH: "Xiaogan, China",
    WUX: "Wuxi, China",
    XIY: "Baoji, China",
    XMN: "Xiamen",
    XNH: "Nasiriyah, Iraq",
    YOW: "Ottawa, Canada",
    YUL: "Montréal, QC, Canada",
    YVR: "Vancouver, BC, Canada",
    YWG: "Winnipeg, MB, Canada",
    YXE: "Saskatoon, SK, Canada",
    YYC: "Calgary, AB, Canada",
    YYZ: "Toronto, ON, Canada",
    ZAG: "Zagreb, Croatia",
    ZDM: "Ramallah",
    ZGN: "Zhongshan, China",
    ZRH: "Zürich, Switzerland"
}

const code_name = (document.getElementById("ray-id") as HTMLSpanElement).innerText.split("-")[1];
if (code_name) {
    if (code_name in CFDataCenterMap) {
        (document.getElementById("ray-id-detail") as HTMLSpanElement).innerText = CFDataCenterMap[code_name];
    }
}
